version: "3"
services:

  redis:
    image: redis:alpine
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"

  db:
    image: postgres
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"

  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    restart: always
    networks:
      - back-tier
    environment:
      - 0.0.0.0

  pool:
    build: ./poll
    depends_on:
      - redis
    links:
      - redis
    restart: always
    ports:
      - "5000:80"
    networks:
      - poll-tier
    environment:
      - 0.0.0.0

  result:
    build: ./result
    depends_on:
      - db
    links:
      - db
    restart: always
    ports:
      - "5001:80"
    networks:
      - result-tier
    environment:
      - 0.0.0.0
      - NODE_ENV=development
      - FLASK_ENV=development

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: