FROM python:3.8-slim-buster

RUN apt-get update -y && \
    apt-get install -y python3-pip python3-dev

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 80
CMD ["flask", "run", "--host=0.0.0.0", "--port=80"]